
import { AiFillStar } from "react-icons/ai";

export const DataList = [
  {
    id: 0,
    img: `${require('../img/littleheadphone.png')}`,
    title: "Wireless headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Razer",
    color: "black",
    category: "Headphones"
  },
  {
    id: 1,
    img: `${require('../img/joystick.png')}`,
    title: "PLay game",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Sony",
    color: "black",
    category: "Console",
  },
  {
    id: 2,
    img: `${require('../img/desktop.png')}`,
    title: "Tablet as a laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Asus",
    color: "white",
    category: "Laptop"
  },
  {
    id: 3,
    img: `${require('../img/littleheadphone.png')}`,
    title: "Wireless headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Razer",
    color: "black",
    category: "Headphones",
  },
  {
    id: 4,
    img: `${require('../img/joystick.png')}`,
    title: "PLay game",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Sony",
    color: "black",
    category: "Console"
  },
  {
    id: 5,
    img: `${require('../img/desktop.png')}`,
    title: "Tablet as a laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Asus",
    color: "white",
    category: "Laptop",
  },
  {
    id: 6,
    img: `${require('../img/littleheadphone.png')}`,
    title: "Wireless headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Razer",
    color: "black",
    category: "Headphones"
  },
  {
    id: 7,
    img: `${require('../img/joystick.png')}`,
    title: "PLay game",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Sony",
    color: "black",
    category: "Console",
  },
  {
    id: 8,
    img: `${require('../img/desktop.png')}`,
    title: "Tablet as a laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Asus",
    color: "white",
    category: "Laptop"
  },
  {
    id: 9,
    img: `${require('../img/littleheadphone.png')}`,
    title: "Wireless headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Razer",
    color: "black",
    category: "Headphones"
  },
  {
    id: 10,
    img: `${require('../img/joystick.png')}`,
    title: "PLay game",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Sony",
    color: "black",
    category: "Console",
  },
  {
    id: 11,
    img: `${require('../img/desktop.png')}`,
    title: "Tablet as a laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Asus",
    color: "white",
    category: "Laptop"
  },
  {
    id: 12,
    img: `${require('../img/littleheadphone.png')}`,
    title: "Wireless headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Razer",
    color: "black",
    category: "Headphones"
  },
  {
    id: 13,
    img: `${require('../img/joystick.png')}`,
    title: "PLay game",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Sony",
    color: "black",
    category: "Console",
  },
  {
    id: 14,
    img: `${require('../img/desktop.png')}`,
    title: "Tablet as a laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$11,70",
    company: "Asus",
    color: "white",
    category: "Laptop"
  }
];
